export default {

	// Router
	ROUTER_LOCATION_CHANGE: '@@router/LOCATION_CHANGE',

	// Catalog
	CATALOG_ITEMS_RESOLVED: 'CATALOG_ITEMS_RESOLVED',
	CATALOG_ITEMS_REJECTED: 'CATALOG_ITEMS_REJECTED',
	CATALOG_CLEAR_STATE: 'CATALOG_CLEAR_STATE',

	// Cart
	CART_ADD_ITEM: 'CART_ADD_ITEM',
	CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
	CART_CHANGE_ITEM_COUNT: 'CART_CHANGE_ITEM_COUNT',
	CART_SORT_ITEMS: 'CART_SORT_ITEMS',
}
